//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_accounts
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public string currency_code { get; set; }
        public double opening_balance { get; set; }
        public string bank_name { get; set; }
        public string bank_phone { get; set; }
        public string bank_address { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_bill_histories
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int bill_id { get; set; }
        public string status_code { get; set; }
        public bool notify { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_bill_item_taxes
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int bill_id { get; set; }
        public int bill_item_id { get; set; }
        public int tax_id { get; set; }
        public string name { get; set; }
        public double amount { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_bill_items
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int bill_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public string name { get; set; }
        public string sku { get; set; }
        public double quantity { get; set; }
        public double price { get; set; }
        public double total { get; set; }
        public double tax { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_bill_payments
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int bill_id { get; set; }
        public int account_id { get; set; }
        public System.DateTime paid_at { get; set; }
        public double amount { get; set; }
        public string currency_code { get; set; }
        public double currency_rate { get; set; }
        public string description { get; set; }
        public string payment_method { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public bool reconciled { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_bill_statuses
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_bill_totals
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int bill_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public double amount { get; set; }
        public int sort_order { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_bills
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string bill_number { get; set; }
        public string order_number { get; set; }
        public string bill_status_code { get; set; }
        public System.DateTime billed_at { get; set; }
        public System.DateTime due_at { get; set; }
        public double amount { get; set; }
        public string currency_code { get; set; }
        public double currency_rate { get; set; }
        public int vendor_id { get; set; }
        public string vendor_name { get; set; }
        public string vendor_email { get; set; }
        public string vendor_tax_number { get; set; }
        public string vendor_phone { get; set; }
        public string vendor_address { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public int category_id { get; set; }
        public int parent_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_categories
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string color { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_companies
    {
        public long id { get; set; }
        public string domain { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_currencies
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public double rate { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string precision { get; set; }
        public string symbol { get; set; }
        public int symbol_first { get; set; }
        public string decimal_mark { get; set; }
        public string thousands_separator { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_customers
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string tax_number { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string website { get; set; }
        public string currency_code { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string reference { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_failed_jobs
    {
        public decimal id { get; set; }
        public string connection { get; set; }
        public string queue { get; set; }
        public string payload { get; set; }
        public string exception { get; set; }
        public System.DateTime failed_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_invoice_histories
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int invoice_id { get; set; }
        public string status_code { get; set; }
        public bool notify { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_invoice_item_taxes
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int invoice_id { get; set; }
        public int invoice_item_id { get; set; }
        public int tax_id { get; set; }
        public string name { get; set; }
        public double amount { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_invoice_items
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int invoice_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public string name { get; set; }
        public string sku { get; set; }
        public double quantity { get; set; }
        public double price { get; set; }
        public double total { get; set; }
        public double tax { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_invoice_payments
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int invoice_id { get; set; }
        public int account_id { get; set; }
        public System.DateTime paid_at { get; set; }
        public double amount { get; set; }
        public string currency_code { get; set; }
        public double currency_rate { get; set; }
        public string description { get; set; }
        public string payment_method { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public bool reconciled { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_invoice_statuses
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_invoice_totals
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int invoice_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public double amount { get; set; }
        public int sort_order { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_invoices
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string invoice_number { get; set; }
        public string order_number { get; set; }
        public string invoice_status_code { get; set; }
        public System.DateTime invoiced_at { get; set; }
        public System.DateTime due_at { get; set; }
        public double amount { get; set; }
        public string currency_code { get; set; }
        public double currency_rate { get; set; }
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string customer_email { get; set; }
        public string customer_tax_number { get; set; }
        public string customer_phone { get; set; }
        public string customer_address { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public int category_id { get; set; }
        public int parent_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_items
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string name { get; set; }
        public string sku { get; set; }
        public string description { get; set; }
        public double sale_price { get; set; }
        public double purchase_price { get; set; }
        public int quantity { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> tax_id { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_jobs
    {
        public decimal id { get; set; }
        public string queue { get; set; }
        public string payload { get; set; }
        public byte attempts { get; set; }
        public Nullable<long> reserved_at { get; set; }
        public long available_at { get; set; }
        public long created_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_media
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vzb_media()
        {
            this.vzb_mediables = new HashSet<vzb_mediables>();
        }
    
        public long id { get; set; }
        public string disk { get; set; }
        public string directory { get; set; }
        public string filename { get; set; }
        public string extension { get; set; }
        public string mime_type { get; set; }
        public string aggregate_type { get; set; }
        public long size { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vzb_mediables> vzb_mediables { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_mediables
    {
        public long media_id { get; set; }
        public string mediable_type { get; set; }
        public long mediable_id { get; set; }
        public string tag { get; set; }
        public long order { get; set; }
    
        public virtual vzb_media vzb_media { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_migrations
    {
        public long id { get; set; }
        public string migration { get; set; }
        public int batch { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_module_histories
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int module_id { get; set; }
        public string category { get; set; }
        public string version { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_modules
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string alias { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_notifications
    {
        public System.Guid id { get; set; }
        public string type { get; set; }
        public long notifiable_id { get; set; }
        public string notifiable_type { get; set; }
        public string data { get; set; }
        public Nullable<System.DateTime> read_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_password_resets
    {
        public string email { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_payments
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int account_id { get; set; }
        public System.DateTime paid_at { get; set; }
        public double amount { get; set; }
        public string currency_code { get; set; }
        public double currency_rate { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public string description { get; set; }
        public int category_id { get; set; }
        public string payment_method { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public int parent_id { get; set; }
        public bool reconciled { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_permissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vzb_permissions()
        {
            this.vzb_user_permissions = new HashSet<vzb_user_permissions>();
            this.vzb_roles = new HashSet<vzb_roles>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string display_name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vzb_user_permissions> vzb_user_permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vzb_roles> vzb_roles { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_reconciliations
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int account_id { get; set; }
        public System.DateTime started_at { get; set; }
        public System.DateTime ended_at { get; set; }
        public double closing_balance { get; set; }
        public bool reconciled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_recurring
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public long recurable_id { get; set; }
        public string recurable_type { get; set; }
        public string frequency { get; set; }
        public int interval { get; set; }
        public System.DateTime started_at { get; set; }
        public int count { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_revenues
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int account_id { get; set; }
        public System.DateTime paid_at { get; set; }
        public double amount { get; set; }
        public string currency_code { get; set; }
        public double currency_rate { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string description { get; set; }
        public int category_id { get; set; }
        public string payment_method { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public int parent_id { get; set; }
        public bool reconciled { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vzb_roles()
        {
            this.vzb_user_roles = new HashSet<vzb_user_roles>();
            this.vzb_permissions = new HashSet<vzb_permissions>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string display_name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vzb_user_roles> vzb_user_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vzb_permissions> vzb_permissions { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_sessions
    {
        public string id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string ip_address { get; set; }
        public string user_agent { get; set; }
        public string payload { get; set; }
        public int last_activity { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_settings
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string key { get; set; }
        public string value { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_taxes
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public string name { get; set; }
        public double rate { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string type { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_transfers
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public int payment_id { get; set; }
        public int revenue_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_user_companies
    {
        public long user_id { get; set; }
        public long company_id { get; set; }
        public string user_type { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_user_permissions
    {
        public long user_id { get; set; }
        public long permission_id { get; set; }
        public string user_type { get; set; }
    
        public virtual vzb_permissions vzb_permissions { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_user_roles
    {
        public long user_id { get; set; }
        public long role_id { get; set; }
        public string user_type { get; set; }
    
        public virtual vzb_roles vzb_roles { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_users
    {
        public long id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string remember_token { get; set; }
        public Nullable<System.DateTime> last_logged_in_at { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string locale { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vzb_vendors
    {
        public long id { get; set; }
        public int company_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string tax_number { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string website { get; set; }
        public string currency_code { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string reference { get; set; }
    }
}
