//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuhasebeEntities : DbContext
    {
        public MuhasebeEntities()
            : base("name=MuhasebeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vzb_accounts> vzb_accounts { get; set; }
        public virtual DbSet<vzb_bill_histories> vzb_bill_histories { get; set; }
        public virtual DbSet<vzb_bill_item_taxes> vzb_bill_item_taxes { get; set; }
        public virtual DbSet<vzb_bill_items> vzb_bill_items { get; set; }
        public virtual DbSet<vzb_bill_payments> vzb_bill_payments { get; set; }
        public virtual DbSet<vzb_bill_statuses> vzb_bill_statuses { get; set; }
        public virtual DbSet<vzb_bill_totals> vzb_bill_totals { get; set; }
        public virtual DbSet<vzb_bills> vzb_bills { get; set; }
        public virtual DbSet<vzb_categories> vzb_categories { get; set; }
        public virtual DbSet<vzb_companies> vzb_companies { get; set; }
        public virtual DbSet<vzb_currencies> vzb_currencies { get; set; }
        public virtual DbSet<vzb_customers> vzb_customers { get; set; }
        public virtual DbSet<vzb_failed_jobs> vzb_failed_jobs { get; set; }
        public virtual DbSet<vzb_invoice_histories> vzb_invoice_histories { get; set; }
        public virtual DbSet<vzb_invoice_item_taxes> vzb_invoice_item_taxes { get; set; }
        public virtual DbSet<vzb_invoice_items> vzb_invoice_items { get; set; }
        public virtual DbSet<vzb_invoice_payments> vzb_invoice_payments { get; set; }
        public virtual DbSet<vzb_invoice_statuses> vzb_invoice_statuses { get; set; }
        public virtual DbSet<vzb_invoice_totals> vzb_invoice_totals { get; set; }
        public virtual DbSet<vzb_invoices> vzb_invoices { get; set; }
        public virtual DbSet<vzb_items> vzb_items { get; set; }
        public virtual DbSet<vzb_jobs> vzb_jobs { get; set; }
        public virtual DbSet<vzb_media> vzb_media { get; set; }
        public virtual DbSet<vzb_mediables> vzb_mediables { get; set; }
        public virtual DbSet<vzb_migrations> vzb_migrations { get; set; }
        public virtual DbSet<vzb_module_histories> vzb_module_histories { get; set; }
        public virtual DbSet<vzb_modules> vzb_modules { get; set; }
        public virtual DbSet<vzb_notifications> vzb_notifications { get; set; }
        public virtual DbSet<vzb_payments> vzb_payments { get; set; }
        public virtual DbSet<vzb_permissions> vzb_permissions { get; set; }
        public virtual DbSet<vzb_reconciliations> vzb_reconciliations { get; set; }
        public virtual DbSet<vzb_recurring> vzb_recurring { get; set; }
        public virtual DbSet<vzb_revenues> vzb_revenues { get; set; }
        public virtual DbSet<vzb_roles> vzb_roles { get; set; }
        public virtual DbSet<vzb_settings> vzb_settings { get; set; }
        public virtual DbSet<vzb_taxes> vzb_taxes { get; set; }
        public virtual DbSet<vzb_transfers> vzb_transfers { get; set; }
        public virtual DbSet<vzb_user_companies> vzb_user_companies { get; set; }
        public virtual DbSet<vzb_user_permissions> vzb_user_permissions { get; set; }
        public virtual DbSet<vzb_user_roles> vzb_user_roles { get; set; }
        public virtual DbSet<vzb_users> vzb_users { get; set; }
        public virtual DbSet<vzb_vendors> vzb_vendors { get; set; }
        public virtual DbSet<vzb_password_resets> vzb_password_resets { get; set; }
        public virtual DbSet<vzb_sessions> vzb_sessions { get; set; }
    }
}
