//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_address
    {
        public int address_id { get; set; }
        public int customer_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string company { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public int country_id { get; set; }
        public int zone_id { get; set; }
        public string custom_field { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_api
    {
        public int api_id { get; set; }
        public string username { get; set; }
        public string key { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_api_ip
    {
        public int api_ip_id { get; set; }
        public int api_id { get; set; }
        public string ip { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_api_session
    {
        public int api_session_id { get; set; }
        public int api_id { get; set; }
        public string session_id { get; set; }
        public string ip { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_attribute
    {
        public int attribute_id { get; set; }
        public int attribute_group_id { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_attribute_description
    {
        public int attribute_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_attribute_group
    {
        public int attribute_group_id { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_attribute_group_description
    {
        public int attribute_group_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_banner
    {
        public int banner_id { get; set; }
        public string name { get; set; }
        public bool status { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_banner_image
    {
        public int banner_image_id { get; set; }
        public int banner_id { get; set; }
        public int language_id { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public string image { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_cart
    {
        public long cart_id { get; set; }
        public int api_id { get; set; }
        public int customer_id { get; set; }
        public string session_id { get; set; }
        public int product_id { get; set; }
        public int recurring_id { get; set; }
        public string option { get; set; }
        public int quantity { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_category
    {
        public int category_id { get; set; }
        public string image { get; set; }
        public int parent_id { get; set; }
        public bool top { get; set; }
        public int column { get; set; }
        public int sort_order { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_category_description
    {
        public int category_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string meta_title { get; set; }
        public string meta_description { get; set; }
        public string meta_keyword { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_category_filter
    {
        public int category_id { get; set; }
        public int filter_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_category_path
    {
        public int category_id { get; set; }
        public int path_id { get; set; }
        public int level { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_category_to_layout
    {
        public int category_id { get; set; }
        public int store_id { get; set; }
        public int layout_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_category_to_store
    {
        public int category_id { get; set; }
        public int store_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_country
    {
        public int country_id { get; set; }
        public string name { get; set; }
        public string iso_code_2 { get; set; }
        public string iso_code_3 { get; set; }
        public string address_format { get; set; }
        public bool postcode_required { get; set; }
        public bool status { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_coupon
    {
        public int coupon_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public decimal discount { get; set; }
        public bool logged { get; set; }
        public bool shipping { get; set; }
        public decimal total { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
        public int uses_total { get; set; }
        public string uses_customer { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_coupon_category
    {
        public int coupon_id { get; set; }
        public int category_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_coupon_history
    {
        public int coupon_history_id { get; set; }
        public int coupon_id { get; set; }
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_coupon_product
    {
        public int coupon_product_id { get; set; }
        public int coupon_id { get; set; }
        public int product_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_currency
    {
        public int currency_id { get; set; }
        public string title { get; set; }
        public string code { get; set; }
        public string symbol_left { get; set; }
        public string symbol_right { get; set; }
        public string decimal_place { get; set; }
        public double value { get; set; }
        public bool status { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_custom_field
    {
        public int custom_field_id { get; set; }
        public string type { get; set; }
        public string value { get; set; }
        public string validation { get; set; }
        public string location { get; set; }
        public bool status { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_custom_field_customer_group
    {
        public int custom_field_id { get; set; }
        public int customer_group_id { get; set; }
        public bool required { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_custom_field_description
    {
        public int custom_field_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_custom_field_value
    {
        public int custom_field_value_id { get; set; }
        public int custom_field_id { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_custom_field_value_description
    {
        public int custom_field_value_id { get; set; }
        public int language_id { get; set; }
        public int custom_field_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer
    {
        public int customer_id { get; set; }
        public int customer_group_id { get; set; }
        public int store_id { get; set; }
        public int language_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string cart { get; set; }
        public string wishlist { get; set; }
        public bool newsletter { get; set; }
        public int address_id { get; set; }
        public string custom_field { get; set; }
        public string ip { get; set; }
        public bool status { get; set; }
        public bool safe { get; set; }
        public string token { get; set; }
        public string code { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_activity
    {
        public int customer_activity_id { get; set; }
        public int customer_id { get; set; }
        public string key { get; set; }
        public string data { get; set; }
        public string ip { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_affiliate
    {
        public int customer_id { get; set; }
        public string company { get; set; }
        public string website { get; set; }
        public string tracking { get; set; }
        public decimal commission { get; set; }
        public string tax { get; set; }
        public string payment { get; set; }
        public string cheque { get; set; }
        public string paypal { get; set; }
        public string bank_name { get; set; }
        public string bank_branch_number { get; set; }
        public string bank_swift_code { get; set; }
        public string bank_account_name { get; set; }
        public string bank_account_number { get; set; }
        public string custom_field { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_approval
    {
        public int customer_approval_id { get; set; }
        public int customer_id { get; set; }
        public string type { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_group
    {
        public int customer_group_id { get; set; }
        public int approval { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_group_description
    {
        public int customer_group_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_history
    {
        public int customer_history_id { get; set; }
        public int customer_id { get; set; }
        public string comment { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_ip
    {
        public int customer_ip_id { get; set; }
        public int customer_id { get; set; }
        public string ip { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_login
    {
        public int customer_login_id { get; set; }
        public string email { get; set; }
        public string ip { get; set; }
        public int total { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_online
    {
        public string ip { get; set; }
        public int customer_id { get; set; }
        public string url { get; set; }
        public string referer { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_reward
    {
        public int customer_reward_id { get; set; }
        public int customer_id { get; set; }
        public int order_id { get; set; }
        public string description { get; set; }
        public int points { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_search
    {
        public int customer_search_id { get; set; }
        public int store_id { get; set; }
        public int language_id { get; set; }
        public int customer_id { get; set; }
        public string keyword { get; set; }
        public Nullable<int> category_id { get; set; }
        public bool sub_category { get; set; }
        public bool description { get; set; }
        public int products { get; set; }
        public string ip { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_transaction
    {
        public int customer_transaction_id { get; set; }
        public int customer_id { get; set; }
        public int order_id { get; set; }
        public string description { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_customer_wishlist
    {
        public int customer_id { get; set; }
        public int product_id { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_download
    {
        public int download_id { get; set; }
        public string filename { get; set; }
        public string mask { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_download_description
    {
        public int download_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_event
    {
        public int event_id { get; set; }
        public string code { get; set; }
        public string trigger { get; set; }
        public string action { get; set; }
        public bool status { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_extension
    {
        public int extension_id { get; set; }
        public string type { get; set; }
        public string code { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_extension_install
    {
        public int extension_install_id { get; set; }
        public int extension_download_id { get; set; }
        public string filename { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_extension_path
    {
        public int extension_path_id { get; set; }
        public int extension_install_id { get; set; }
        public string path { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_filter
    {
        public int filter_id { get; set; }
        public int filter_group_id { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_filter_description
    {
        public int filter_id { get; set; }
        public int language_id { get; set; }
        public int filter_group_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_filter_group
    {
        public int filter_group_id { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_filter_group_description
    {
        public int filter_group_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_geo_zone
    {
        public int geo_zone_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_information
    {
        public int information_id { get; set; }
        public int bottom { get; set; }
        public int sort_order { get; set; }
        public bool status { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_information_description
    {
        public int information_id { get; set; }
        public int language_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string meta_title { get; set; }
        public string meta_description { get; set; }
        public string meta_keyword { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_information_to_layout
    {
        public int information_id { get; set; }
        public int store_id { get; set; }
        public int layout_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_information_to_store
    {
        public int information_id { get; set; }
        public int store_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_language
    {
        public int language_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string locale { get; set; }
        public string image { get; set; }
        public string directory { get; set; }
        public int sort_order { get; set; }
        public bool status { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_layout
    {
        public int layout_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_layout_module
    {
        public int layout_module_id { get; set; }
        public int layout_id { get; set; }
        public string code { get; set; }
        public string position { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_layout_route
    {
        public int layout_route_id { get; set; }
        public int layout_id { get; set; }
        public int store_id { get; set; }
        public string route { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_length_class
    {
        public int length_class_id { get; set; }
        public decimal value { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_length_class_description
    {
        public int length_class_id { get; set; }
        public int language_id { get; set; }
        public string title { get; set; }
        public string unit { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_location
    {
        public int location_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string geocode { get; set; }
        public string image { get; set; }
        public string open { get; set; }
        public string comment { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_manufacturer
    {
        public int manufacturer_id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_manufacturer_to_store
    {
        public int manufacturer_id { get; set; }
        public int store_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_marketing
    {
        public int marketing_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public int clicks { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_modification
    {
        public int modification_id { get; set; }
        public int extension_install_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string author { get; set; }
        public string version { get; set; }
        public string link { get; set; }
        public string xml { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
        public int extension_download_id { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_module
    {
        public int module_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string setting { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_option
    {
        public int option_id { get; set; }
        public string type { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_option_description
    {
        public int option_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_option_value
    {
        public int option_value_id { get; set; }
        public int option_id { get; set; }
        public string image { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_option_value_description
    {
        public int option_value_id { get; set; }
        public int language_id { get; set; }
        public int option_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order
    {
        public int order_id { get; set; }
        public int invoice_no { get; set; }
        public string invoice_prefix { get; set; }
        public int store_id { get; set; }
        public string store_name { get; set; }
        public string store_url { get; set; }
        public int customer_id { get; set; }
        public int customer_group_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string custom_field { get; set; }
        public string payment_firstname { get; set; }
        public string payment_lastname { get; set; }
        public string payment_company { get; set; }
        public string payment_address_1 { get; set; }
        public string payment_address_2 { get; set; }
        public string payment_city { get; set; }
        public string payment_postcode { get; set; }
        public string payment_country { get; set; }
        public int payment_country_id { get; set; }
        public string payment_zone { get; set; }
        public int payment_zone_id { get; set; }
        public string payment_address_format { get; set; }
        public string payment_custom_field { get; set; }
        public string payment_method { get; set; }
        public string payment_code { get; set; }
        public string shipping_firstname { get; set; }
        public string shipping_lastname { get; set; }
        public string shipping_company { get; set; }
        public string shipping_address_1 { get; set; }
        public string shipping_address_2 { get; set; }
        public string shipping_city { get; set; }
        public string shipping_postcode { get; set; }
        public string shipping_country { get; set; }
        public int shipping_country_id { get; set; }
        public string shipping_zone { get; set; }
        public int shipping_zone_id { get; set; }
        public string shipping_address_format { get; set; }
        public string shipping_custom_field { get; set; }
        public string shipping_method { get; set; }
        public string shipping_code { get; set; }
        public string comment { get; set; }
        public decimal total { get; set; }
        public int order_status_id { get; set; }
        public int affiliate_id { get; set; }
        public decimal commission { get; set; }
        public int marketing_id { get; set; }
        public string tracking { get; set; }
        public int language_id { get; set; }
        public int currency_id { get; set; }
        public string currency_code { get; set; }
        public decimal currency_value { get; set; }
        public string ip { get; set; }
        public string forwarded_ip { get; set; }
        public string user_agent { get; set; }
        public string accept_language { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_history
    {
        public int order_history_id { get; set; }
        public int order_id { get; set; }
        public int order_status_id { get; set; }
        public bool notify { get; set; }
        public string comment { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_option
    {
        public int order_option_id { get; set; }
        public int order_id { get; set; }
        public int order_product_id { get; set; }
        public int product_option_id { get; set; }
        public int product_option_value_id { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public string type { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_product
    {
        public int order_product_id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public decimal total { get; set; }
        public decimal tax { get; set; }
        public int reward { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_recurring
    {
        public int order_recurring_id { get; set; }
        public int order_id { get; set; }
        public string reference { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int product_quantity { get; set; }
        public int recurring_id { get; set; }
        public string recurring_name { get; set; }
        public string recurring_description { get; set; }
        public string recurring_frequency { get; set; }
        public short recurring_cycle { get; set; }
        public short recurring_duration { get; set; }
        public decimal recurring_price { get; set; }
        public bool trial { get; set; }
        public string trial_frequency { get; set; }
        public short trial_cycle { get; set; }
        public short trial_duration { get; set; }
        public decimal trial_price { get; set; }
        public sbyte status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_recurring_transaction
    {
        public int order_recurring_transaction_id { get; set; }
        public int order_recurring_id { get; set; }
        public string reference { get; set; }
        public string type { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_shipment
    {
        public int order_shipment_id { get; set; }
        public int order_id { get; set; }
        public System.DateTime date_added { get; set; }
        public string shipping_courier_id { get; set; }
        public string tracking_number { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_status
    {
        public int order_status_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_total
    {
        public int order_total_id { get; set; }
        public int order_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public decimal value { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_order_voucher
    {
        public int order_voucher_id { get; set; }
        public int order_id { get; set; }
        public int voucher_id { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public string from_name { get; set; }
        public string from_email { get; set; }
        public string to_name { get; set; }
        public string to_email { get; set; }
        public int voucher_theme_id { get; set; }
        public string message { get; set; }
        public decimal amount { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product
    {
        public int product_id { get; set; }
        public string model { get; set; }
        public string sku { get; set; }
        public string upc { get; set; }
        public string ean { get; set; }
        public string jan { get; set; }
        public string isbn { get; set; }
        public string mpn { get; set; }
        public string location { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> stock_status_id { get; set; }
        public string image { get; set; }
        public Nullable<int> manufacturer_id { get; set; }
        public Nullable<bool> shipping { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> tax_class_id { get; set; }
        public Nullable<System.DateTime> date_available { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> weight_class_id { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<int> length_class_id { get; set; }
        public Nullable<bool> subtract { get; set; }
        public Nullable<int> minimum { get; set; }
        public Nullable<int> sort_order { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> viewed { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_attribute
    {
        public int product_id { get; set; }
        public int attribute_id { get; set; }
        public int language_id { get; set; }
        public string text { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_description
    {
        public int product_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string tag { get; set; }
        public string meta_title { get; set; }
        public string meta_description { get; set; }
        public string meta_keyword { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_discount
    {
        public int product_discount_id { get; set; }
        public int product_id { get; set; }
        public int customer_group_id { get; set; }
        public int quantity { get; set; }
        public int priority { get; set; }
        public decimal price { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_filter
    {
        public int product_id { get; set; }
        public int filter_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_image
    {
        public int product_image_id { get; set; }
        public int product_id { get; set; }
        public string image { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_option
    {
        public int product_option_id { get; set; }
        public int product_id { get; set; }
        public int option_id { get; set; }
        public string value { get; set; }
        public bool required { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_option_value
    {
        public int product_option_value_id { get; set; }
        public int product_option_id { get; set; }
        public int product_id { get; set; }
        public int option_id { get; set; }
        public int option_value_id { get; set; }
        public int quantity { get; set; }
        public bool subtract { get; set; }
        public decimal price { get; set; }
        public string price_prefix { get; set; }
        public int points { get; set; }
        public string points_prefix { get; set; }
        public decimal weight { get; set; }
        public string weight_prefix { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_recurring
    {
        public int product_id { get; set; }
        public int recurring_id { get; set; }
        public int customer_group_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_related
    {
        public int product_id { get; set; }
        public int related_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_reward
    {
        public int product_reward_id { get; set; }
        public int product_id { get; set; }
        public int customer_group_id { get; set; }
        public int points { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_special
    {
        public int product_special_id { get; set; }
        public int product_id { get; set; }
        public int customer_group_id { get; set; }
        public int priority { get; set; }
        public decimal price { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_to_category
    {
        public int product_id { get; set; }
        public int category_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_to_download
    {
        public int product_id { get; set; }
        public int download_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_to_layout
    {
        public int product_id { get; set; }
        public int store_id { get; set; }
        public int layout_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_product_to_store
    {
        public int product_id { get; set; }
        public int store_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_recurring
    {
        public int recurring_id { get; set; }
        public decimal price { get; set; }
        public string frequency { get; set; }
        public long duration { get; set; }
        public long cycle { get; set; }
        public sbyte trial_status { get; set; }
        public decimal trial_price { get; set; }
        public string trial_frequency { get; set; }
        public long trial_duration { get; set; }
        public long trial_cycle { get; set; }
        public sbyte status { get; set; }
        public int sort_order { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_recurring_description
    {
        public int recurring_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_return
    {
        public int return_id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string product { get; set; }
        public string model { get; set; }
        public int quantity { get; set; }
        public bool opened { get; set; }
        public int return_reason_id { get; set; }
        public int return_action_id { get; set; }
        public int return_status_id { get; set; }
        public string comment { get; set; }
        public System.DateTime date_ordered { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_return_action
    {
        public int return_action_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_return_history
    {
        public int return_history_id { get; set; }
        public int return_id { get; set; }
        public int return_status_id { get; set; }
        public bool notify { get; set; }
        public string comment { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_return_reason
    {
        public int return_reason_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_return_status
    {
        public int return_status_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_review
    {
        public int review_id { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        public string author { get; set; }
        public string text { get; set; }
        public int rating { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_seo_url
    {
        public int seo_url_id { get; set; }
        public int store_id { get; set; }
        public int language_id { get; set; }
        public string query { get; set; }
        public string keyword { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_session
    {
        public string session_id { get; set; }
        public string data { get; set; }
        public System.DateTime expire { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_setting
    {
        public int setting_id { get; set; }
        public int store_id { get; set; }
        public string code { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public bool serialized { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_shipping_courier
    {
        public int shipping_courier_id { get; set; }
        public string shipping_courier_code { get; set; }
        public string shipping_courier_name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_simple_blog_category
    {
        public int simple_blog_category_id { get; set; }
        public string image { get; set; }
        public int parent_id { get; set; }
        public bool top { get; set; }
        public int blog_category_column { get; set; }
        public string external_link { get; set; }
        public int column { get; set; }
        public int sort_order { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_simple_blog_category_description
    {
        public int simple_blog_category_description_id { get; set; }
        public int simple_blog_category_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string meta_description { get; set; }
        public string meta_keyword { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_soconfig
    {
        public int id { get; set; }
        public int store_id { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public bool serialized { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_statistics
    {
        public int statistics_id { get; set; }
        public string code { get; set; }
        public decimal value { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_stock_status
    {
        public int stock_status_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_store
    {
        public int store_id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string ssl { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_tax_class
    {
        public int tax_class_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_tax_rate
    {
        public int tax_rate_id { get; set; }
        public int geo_zone_id { get; set; }
        public string name { get; set; }
        public decimal rate { get; set; }
        public string type { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_tax_rate_to_customer_group
    {
        public int tax_rate_id { get; set; }
        public int customer_group_id { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_tax_rule
    {
        public int tax_rule_id { get; set; }
        public int tax_class_id { get; set; }
        public int tax_rate_id { get; set; }
        public string based { get; set; }
        public int priority { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_theme
    {
        public int theme_id { get; set; }
        public int store_id { get; set; }
        public string theme { get; set; }
        public string route { get; set; }
        public string code { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_translation
    {
        public int translation_id { get; set; }
        public int store_id { get; set; }
        public int language_id { get; set; }
        public string route { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_upload
    {
        public int upload_id { get; set; }
        public string name { get; set; }
        public string filename { get; set; }
        public string code { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_user
    {
        public int user_id { get; set; }
        public int user_group_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string image { get; set; }
        public string code { get; set; }
        public string ip { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_user_group
    {
        public int user_group_id { get; set; }
        public string name { get; set; }
        public string permission { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_voucher
    {
        public int voucher_id { get; set; }
        public int order_id { get; set; }
        public string code { get; set; }
        public string from_name { get; set; }
        public string from_email { get; set; }
        public string to_name { get; set; }
        public string to_email { get; set; }
        public int voucher_theme_id { get; set; }
        public string message { get; set; }
        public decimal amount { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_voucher_history
    {
        public int voucher_history_id { get; set; }
        public int voucher_id { get; set; }
        public int order_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_voucher_theme
    {
        public int voucher_theme_id { get; set; }
        public string image { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_voucher_theme_description
    {
        public int voucher_theme_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_weight_class
    {
        public int weight_class_id { get; set; }
        public decimal value { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_weight_class_description
    {
        public int weight_class_id { get; set; }
        public int language_id { get; set; }
        public string title { get; set; }
        public string unit { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_zone
    {
        public int zone_id { get; set; }
        public int country_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public bool status { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oc_zone_to_geo_zone
    {
        public int zone_to_geo_zone_id { get; set; }
        public int country_id { get; set; }
        public int zone_id { get; set; }
        public int geo_zone_id { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
